server:
  port: 3000
  servlet:
    context-path: /payment
spring:
  boot:
    admin:
      client:
        url: http://host.docker.internal:8888
  application:
    name: PAYMENT-SERVICE
  ########### Database Config ############
  datasource:
    url: jdbc:h2:file:./database/payment_db
    driverClasName: org.h2.Driver
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enable: true
  cloud:
    discovery:
      enabled: true
########### Database Config ############
eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka
  instance:
    prefer-ip-address: true